# -*- coding: utf-8 -*-
{
    'name': 'OTD Marketplace Stock',
    'version': '19.0.1.0.0',
    'summary': 'Central stock & marketplace integrations (Shopee, Lazada, TikTok)',
    'category': 'Inventory/Sales',
    'author': 'OTD',
    'website': 'https://www.odoo.com',
    'license': 'LGPL-3',
    'depends': [
        'sale_management',
        'stock',
        'contacts',
        'mail',
    ],
    'external_dependencies': {
        'python': ['requests'],
    },
    'data': [
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'data/ir_cron_data.xml',
        'data/sequences.xml',
        'views/res_config_settings_views.xml',
        'views/marketplace_account_views.xml',
        'views/marketplace_shop_views.xml',
        'views/lazada_shop_wizard_views.xml',
        'views/product_binding_views.xml',
        'views/order_views.xml',
        'views/sync_rule_views.xml',
        'views/job_queue_views.xml',
        'views/pull_orders_wizard_views.xml',
        'views/dashboard_views.xml',
        'views/enable_track_inventory_wizard_views.xml',
        'views/sale_order_views.xml',
        'views/menu.xml',
        'views/oauth_templates.xml',
        'data/marketplace_channel_data.xml',
        'data/update_action_contexts.xml',
        'data/download_skipped_products_action.xml',
        'data/ir_config_parameter_data.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'otd_marketplace_stock/static/src/scss/lazada_dashboard.scss',
            'otd_marketplace_stock/static/src/scss/lazada_wizard.scss',
            'otd_marketplace_stock/static/src/js/password_toggle_field.js',
            'otd_marketplace_stock/static/src/xml/password_toggle_field.xml',
    ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
}

